#!/bin/bash
# Finalize Ralph work by merging feature branch to main
# Run this when all features are complete

set -e

CONFIG=".ralph/config.yaml"

if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: Config not found at $CONFIG"
    exit 1
fi

DEFAULT_BRANCH=$(yq '.git.default_branch // "main"' "$CONFIG")
FEATURE_BRANCH=$(yq '.git.feature_branch // "ralph/feature"' "$CONFIG")

echo "=== Finalizing Ralph Work ==="
echo "Feature branch: $FEATURE_BRANCH"
echo "Target branch: $DEFAULT_BRANCH"
echo ""

# Check feature status
TOTAL=$(jq '.features | length' .ralph/state/features.json)
PASSING=$(jq '[.features[] | select(.passes==true)] | length' .ralph/state/features.json)
PENDING=$(jq '[.features[] | select(.passes==false)] | length' .ralph/state/features.json)

echo "Feature status: $PASSING / $TOTAL complete"

if [[ "$PENDING" -gt 0 ]]; then
    echo ""
    echo "WARNING: $PENDING features are not complete!"
    echo ""
    jq -r '.features[] | select(.passes==false) | "  - \(.id): \(.description)"' .ralph/state/features.json
    echo ""
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# Check for open PRs
OPEN_PRS=$(gh pr list --base "$FEATURE_BRANCH" --state open --json number -q 'length' 2> /dev/null || echo "0")
if [[ "$OPEN_PRS" -gt 0 ]]; then
    echo ""
    echo "WARNING: $OPEN_PRS open PRs targeting $FEATURE_BRANCH"
    gh pr list --base "$FEATURE_BRANCH" --state open
    echo ""
    read -p "Merge them first? (Y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        gh pr list --base "$FEATURE_BRANCH" --state open --json number -q '.[].number' \
            | xargs -I {} gh pr merge {} --squash --delete-branch
        echo "PRs merged."
    fi
fi

# Ensure feature branch is up to date
echo ""
echo "Updating feature branch..."
git checkout "$FEATURE_BRANCH"
git pull origin "$FEATURE_BRANCH"

# Create PR to merge feature branch to main
echo ""
echo "Creating PR to merge $FEATURE_BRANCH into $DEFAULT_BRANCH..."

PROJECT_NAME=$(yq '.project.name // "Ralph Project"' "$CONFIG")

PR_URL=$(gh pr create \
    --title "feat: $PROJECT_NAME - Complete implementation" \
    --base "$DEFAULT_BRANCH" \
    --head "$FEATURE_BRANCH" \
    --body "## Summary

Complete implementation of $PROJECT_NAME via Ralph.

## Features Completed

$PASSING / $TOTAL features implemented.

### Feature List
$(jq -r '.features[] | select(.passes==true) | "- [x] \(.id): \(.description)"' .ralph/state/features.json)

$(if [[ "$PENDING" -gt 0 ]]; then
        echo "### Incomplete Features"
        jq -r '.features[] | select(.passes==false) | "- [ ] \(.id): \(.description)"' .ralph/state/features.json
    fi)

## Verification

- All feature PRs have been merged to \`$FEATURE_BRANCH\`
- CI checks should pass

---
*Generated by [Ralph](https://github.com/sqds/ralph)*")

echo ""
echo "=== PR Created ==="
echo "$PR_URL"
echo ""
echo "Next steps:"
echo "  1. Review the PR"
echo "  2. Ensure CI passes"
echo "  3. Merge to $DEFAULT_BRANCH"
echo "  4. Delete $FEATURE_BRANCH after merge"
