#!/bin/bash
set -e

# Navigate to project root
cd "$(git rev-parse --show-toplevel 2> /dev/null || pwd)"

MAX_AGENTS=${1:-3}
CONFIG=".ralph/config.yaml"

echo "=== Ralph Parallel Loop ==="
echo "Max agents: $MAX_AGENTS"
echo ""

# Check prerequisites
if [[ ! -f ".ralph/state/features.json" ]]; then
    echo "ERROR: No features.json found."
    echo "Run /ralph-plan to generate features first."
    exit 1
fi

# Check if GNU parallel is available, otherwise use bash backgrounding
USE_GNU_PARALLEL=false
if command -v parallel > /dev/null; then
    USE_GNU_PARALLEL=true
fi

# Function to get parallel-ready features
get_parallel_ready() {
    jq -r '
    .features as $all |
    .features[] |
    select(
      .passes == false and
      .parallel_safe == true and
      .pr == null and
      ((.depends_on // []) | all(. as $dep |
        ($all[] | select(.id == $dep) | .passes) == true
      ))
    ) | .id
  ' .ralph/state/features.json
}

# Function to run a single agent
run_agent() {
    local AGENT_ID=$1
    local FEATURE_ID=$2
    local TIMESTAMP=$(date +%Y%m%d-%H%M%S)
    local LOG_FILE=".ralph/logs/${TIMESTAMP}-agent-${AGENT_ID}-${FEATURE_ID}.log"
    local PROJECT_ROOT=$(pwd)

    echo "=== Agent $AGENT_ID: Starting $FEATURE_ID ===" | tee "$LOG_FILE"

    # Setup isolated database
    if [[ -f ".ralph/scripts/agent-db.sh" ]]; then
        source .ralph/scripts/agent-db.sh create "$AGENT_ID"
    fi

    # Get branch config
    local CONFIG=".ralph/config.yaml"
    local FEATURE_BRANCH=$(yq '.git.feature_branch // "ralph/feature"' "$CONFIG")
    local PR_BASE=$(yq '.git.pr_base // .git.feature_branch // "ralph/feature"' "$CONFIG")

    # Fetch and ensure feature branch exists
    git fetch origin "$FEATURE_BRANCH" 2> /dev/null || git fetch origin main 2> /dev/null || true

    # Create PR branch from feature branch (not main)
    git checkout -b "pr/$FEATURE_ID" "origin/$FEATURE_BRANCH" 2> /dev/null || {
        git checkout "pr/$FEATURE_ID" 2> /dev/null || {
            echo "ERROR: Could not create branch pr/$FEATURE_ID" | tee -a "$LOG_FILE"
            return 1
        }
    }

    # Run coding agent (uses model from config.yaml)
    RALPH_FEATURE="$FEATURE_ID" \
        RALPH_AGENT_ID="$AGENT_ID" \
        .ralph/scripts/run-agent.sh coding .ralph/prompts/coding-agent.md 2>&1 | tee -a "$LOG_FILE"

    # Create PR if there are changes
    COMMITS=$(git rev-list "origin/$FEATURE_BRANCH..HEAD" --count 2> /dev/null || echo "0")

    if [[ "$COMMITS" -gt 0 ]]; then
        echo "Pushing branch and creating PR..." | tee -a "$LOG_FILE"
        git push -u origin "pr/$FEATURE_ID" 2>&1 | tee -a "$LOG_FILE"

        DESCRIPTION=$(jq -r ".features[] | select(.id==\"$FEATURE_ID\") | .description" .ralph/state/features.json)

        PR_URL=$(gh pr create \
            --title "feat($FEATURE_ID): $DESCRIPTION" \
            --base "$PR_BASE" \
            --body "Automated PR from Ralph Agent $AGENT_ID

## Feature
- ID: \`$FEATURE_ID\`
- Agent: $AGENT_ID
- Target: \`$PR_BASE\`

## Verification
See CI checks for test results.

---
*Generated by [Ralph](https://github.com/sqds/ralph)*" 2>&1) || true

        if [[ -n "$PR_URL" ]]; then
            PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$' || gh pr view --json number -q .number 2> /dev/null || echo "")
            if [[ -n "$PR_NUM" ]]; then
                # Update features.json with PR number (atomic via temp file)
                jq "(.features[] | select(.id==\"$FEATURE_ID\")).pr = \"#$PR_NUM\"" \
                    .ralph/state/features.json > /tmp/features-$AGENT_ID.json \
                    && mv /tmp/features-$AGENT_ID.json .ralph/state/features.json
                echo "Created PR #$PR_NUM" | tee -a "$LOG_FILE"
            fi
        fi
    else
        echo "No commits to push" | tee -a "$LOG_FILE"
    fi

    # Cleanup
    if [[ -f ".ralph/scripts/agent-db.sh" ]]; then
        source .ralph/scripts/agent-db.sh destroy "$AGENT_ID"
    fi

    git checkout "$FEATURE_BRANCH" 2> /dev/null || git checkout main 2> /dev/null || true

    echo "=== Agent $AGENT_ID: Completed $FEATURE_ID ===" | tee -a "$LOG_FILE"
}

# Export function for parallel
export -f run_agent

# Get ready features
READY_FEATURES=$(get_parallel_ready | head -$MAX_AGENTS)
FEATURE_COUNT=$(echo "$READY_FEATURES" | grep -c . 2> /dev/null || echo "0")

if [[ -z "$READY_FEATURES" || "$FEATURE_COUNT" -eq 0 ]]; then
    echo "No parallel-ready features available."
    echo ""
    echo "Possible reasons:"
    echo "  - All parallel features are complete"
    echo "  - Remaining features have unmet dependencies"
    echo "  - Remaining features are parallel_safe: false"
    echo ""
    echo "Try running sequential loop: .ralph/scripts/loop.sh"
    exit 0
fi

echo "Features to process: $FEATURE_COUNT"
echo "$READY_FEATURES"
echo ""

# Run agents in parallel
if [[ "$USE_GNU_PARALLEL" == "true" ]]; then
    echo "$READY_FEATURES" | nl -v 1 | parallel --jobs "$MAX_AGENTS" --colsep '\t' 'run_agent {1} {2}'
else
    # Fallback: bash background processes
    PIDS=()
    AGENT_NUM=1
    while IFS= read -r FEATURE_ID; do
        run_agent "$AGENT_NUM" "$FEATURE_ID" &
        PIDS+=($!)
        ((AGENT_NUM++))
    done <<< "$READY_FEATURES"

    # Wait for all agents to complete
    for PID in "${PIDS[@]}"; do
        wait "$PID" || true
    done
fi

echo ""
echo "=== Parallel batch complete ==="
echo ""
echo "Check PRs: gh pr list"
echo "Merge ready PRs: gh pr merge <number> --squash"
