language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - develop
      - hotfix
      - .+
  path_instructions:
    - path: "*"
      instructions: |
        PR should be atomic and focused on a single change and doesn't contain a mix of different types of changes (new feature, refactoring and fix in existing code).
        Check new changes are covered by tests and/or existing tests are updated
        Check that existing documentation is updated for new changes
        New changes has enough comments to understand the logic
knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: global
  issues:
    scope: global
  pull_requests:
    scope: global
chat:
  auto_reply: true
