# Botanix Rust Formatting Configuration

# Ignore paths
ignore = ["testing"]

# Edition
edition = "2021"

# Line width
max_width = 80

# Imports
reorder_imports = true

# Modules
reorder_modules = true

# Spacing and indentation
tab_spaces = 4
use_small_heuristics = "Max"

# Code style
use_field_init_shorthand = true
use_try_shorthand = true
