[package]
name = "botanix-rpc-config"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
alloy-eips = { workspace = true }

# other deps
alloy-primitives = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }

# botanix
botanix-authority-edh = { workspace = true }
botanix-btc-server = { workspace = true }
botanix-btc-wallet = { workspace = true }
frost-secp256k1-tr = { workspace = true }
jsonrpsee-core = { workspace = true }
jsonrpsee-types = { workspace = true }

# reth deps
reth-primitives = { workspace = true, features = ["secp256k1"] }
reth-storage-api = { workspace = true }
revm-primitives = { workspace = true }
secp256k1 = { workspace = true, features = ["global-context", "recovery"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
