[package]
name = "botanix-bitcoin-checkpoint"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]

# other deps
arc-swap = "1.7.1"
async-trait = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
bitcoincore-zmq = { workspace = true }

# botanix deps
botanix-btc-wallet = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
