[package]
name = "botanix-rpc-types"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
botanix-authority-edh = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
