[package]
name = "botanix-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# Reth dependencies - using botanix fork
reth-basic-payload-builder = { workspace = true }
reth-chainspec = { workspace = true }
reth-consensus = { workspace = true }
reth-db = { workspace = true, features = ["mdbx"] }
reth-ethereum-engine-primitives = { workspace = true }
reth-ethereum-payload-builder = { workspace = true }
reth-ethereum-primitives = { workspace = true }
reth-evm = { workspace = true }
reth-execution-errors = { workspace = true }
reth-node-types = { workspace = true }
reth-payload-builder = { workspace = true }
reth-payload-primitives = { workspace = true }
reth-primitives = { workspace = true, features = ["secp256k1"] }
reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true }
reth-revm = { workspace = true }
reth-storage-errors = { workspace = true }
reth-transaction-pool = { workspace = true }

# REVM dependencies
revm-database = { workspace = true }

# alloy dependencies
alloy-consensus.workspace = true
alloy-eips.workspace = true

# Botanix
botanix-authority-edh = { workspace = true }
botanix-authority-peg = { workspace = true }
botanix-btc-wallet = { workspace = true }
botanix-chainspec = { workspace = true }
botanix-consensus-common = { workspace = true }

# Bitcoin
bitcoin = { workspace = true }

# BTC Server
btc-server = { workspace = true }

# Misc
derive_more = { workspace = true }

# tracing
tracing = { workspace = true }

[lints]
workspace = true
