[package]
name = "botanix-fs-util"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Commonly used fs utils in reth."

[dependencies]
serde = { workspace = true }
# misc
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
