[package]
name = "botanix-activation-manager"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
# botanix deps
botanix-storage = { workspace = true }

#  reth deps
alloy-primitives = { workspace = true }
reth-storage-errors = { workspace = true }

[features]
test-utils = []
