[package]
name = "botanix-chainspec"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]

# reth deps
reth-chainspec = { workspace = true }
reth-cli = { workspace = true }
reth-ethereum-forks = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-network-peers = { workspace = true }

# ethereum
alloy-chains = { workspace = true, features = ["serde", "rlp"] }
alloy-eips = { workspace = true, features = ["serde"] }
alloy-genesis = { workspace = true }
alloy-primitives = { workspace = true, features = ["rand", "rlp", "serde"] }
alloy-serde = { workspace = true }
alloy-consensus = { workspace = true }
alloy-hardforks = { workspace = true }

# other deps
askama = { workspace = true }
botanix-hardforks = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
derive_more = { workspace = true }
eyre = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shellexpand = { workspace = true }
