[package]
name = "botanix-storage-migrate"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "A library for botanix tables migration from reth to botanix database"

[features]
test-utils = ["reth-db/test-utils", "botanix-storage/test-utils"]

[dependencies]
alloy-primitives = { workspace = true, features = ["std"] }

# botanix
botanix-storage = { workspace = true }
eyre = { workspace = true }

# reth
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api = { workspace = true }
reth-node-types = { workspace = true }
reth-primitives = { workspace = true }

tracing = { workspace = true }

[dev-dependencies]

# botanix deps
botanix-storage = { workspace = true, features = ["test-utils"] }

# reth deps
reth-db = { workspace = true, features = ["mdbx", "test-utils"] }

tempfile = { workspace = true }

[lints]
workspace = true
