# TODO: Define layer caching

services:
  btc_server:
    image: botanix-local-btc-server:latest
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        # This compose file meant to be used only for local development and testing
        PROFILE: dev
        PACKAGE: btc-server
        BIN: btc-server
    command:
      - --identifier=${BTC_SERVER_ID:?err}
      - --coordinator=0
      - --federation-config-path=/app/config/federation.toml
      - --p2p-secret-key=/app/config/discovery-secret
      - --address=0.0.0.0:8080
      - --db=/app/db
      - --min-signers=${FROST_MIN_SIGNERS:?err}
      - --max-signers=${FROST_MAX_SIGNERS:?err}
      - --toml=/app/config/config.toml
      - --fee-rate-diff-percentage=30
      - --btc-network=${BITCOIND_NETWORK:?err}
      - --bitcoind-url=${BITCOIND_URL:?err}
      - --bitcoind-user=${BITCOIND_USER:?err}
      - --bitcoind-pass=${BITCOIND_PASSWORD:?err}
      - --btc-signing-server-jwt-secret=/app/config/bjwt.hex
      - --fall-back-fee-rate-sat-per-vbyte=5
    volumes:
      - ${BOTANIX_HOME:?err}/btc_server:/app/config:ro
      - btc_server_db:/app/db:rw
    ports:
      - 127.0.0.1:${BTC_SERVER_PORT}:8080
    restart: on-failure
    networks:
      - botanix-local

  poa:
    image: botanix-local-poa:latest
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        # This compose file meant to be used only for local development and testing
        PROFILE: dev
        PACKAGE: reth
        BIN: reth
    command:
      - poa
      - --is-testnet
      - --federation-config-path=/app/config/federation.toml
      - --federation-mode
      - --datadir=/app
      - --http
      - --http.corsdomain=*
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.api=eth,net,trace,txpool,web3,rpc,admin
      - --ws
      - --ws.origins=*
      - --ws.port=8546
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,trace,txpool,web3,rpc,admin
      - -vvv
      - --log.stdout.filter=${POA_LOG_STDOUT_FILTER:-block_with_context=off}
      - --btc-server=${COMPOSE_PROJECT_NAME?:err}-btc_server-1:8080
      - --btc-network=${BITCOIND_NETWORK:?err}
      - --btc-signing-server-jwt-secret=/app/config/bjwt.hex
      - --bitcoind.url=${BITCOIND_URL:?err}
      - --bitcoind.username=${BITCOIND_USER:?err}
      - --bitcoind.password=${BITCOIND_PASSWORD:?err}
      - --bitcoind.zmq.hash-block-address=${BITCOIND_ZMQ_HASH_BLOCK_ADDRESS:?err}
      - --frost.min_signers=${FROST_MIN_SIGNERS:?err}
      - --frost.max_signers=${FROST_MAX_SIGNERS:?err}
      - --sync.num_snapshots_to_keep=3
      - --p2p-secret-key=/app/config/discovery-secret
      - --port=30303
      - --sync.enable_state_sync
      - --sync.enable_historical_sync
      - --block-fee-recipient-address=${BLOCK_FEE_RECIPIENT_ADDRESS:?err}
      - --abci-host=0.0.0.0
      - --abci-port=26658
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --metrics=0.0.0.0:9001
      - --ipcdisable
      - --txpool.minimum-priority-fee=2500000
      - --txpool.minimal-protocol-fee=5000000
    ports:
      - 127.0.0.1:${POA_RPC_PORT:?err}:8545 # RPC
      - 127.0.0.1:${POA_WS_PORT:?err}:8546 # Websocket
      - 127.0.0.1:${POA_METRICS_PORT:?err}:9001 # Metrics
    depends_on:
      - btc_server
      - cometbft
    volumes:
      - ${BOTANIX_HOME:?err}/poa:/app/config:ro
      - poa_data:/app:rw
      - poa_logs:/root/.cache/reth/logs:rw
    restart: on-failure
    networks:
      botanix-local:
        ipv4_address: ${POA_IP4_ADDRESS:?err}

  cometbft:
    image: us-central1-docker.pkg.dev/botanix-391913/botanix-betanet-cometbft/botanix-betanet-cometbft:v1
    ports:
      - ${COMET_BFT_RPC_PORT:?err}:26657 # RPC
      - ${COMET_BFT_METRICS_PORT:?err}:26660 # Metrics
    volumes:
      - ${BOTANIX_HOME:?err}/cometbft/config:/home/nonroot/.cometbft/config:ro
      - cometbft_db:/home/nonroot/.cometbft/data:rw
    restart: on-failure
    networks:
      - botanix-local
    environment:
      - LOG_LEVEL=DEBUG
      - NODE_NAME=${COMPOSE_PROJECT_NAME:?err}
      - MONIKER=${COMPOSE_PROJECT_NAME:?err}
      - P2P_ALLOW_DUPLICATE_IP=true
      - P2P_ADDR_BOOK_STRICT=false
    command: start

volumes:
  btc_server_db:
    driver: local

  poa_data:
    driver: local

  poa_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BOTANIX_HOME:?err}/poa/logs

  cometbft_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BOTANIX_HOME:?err}/cometbft/data

networks:
  botanix-local:
    external: true
