services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:24
    hostname: bitcoin-core
    container_name: bitcoin-core
    volumes:
      - ./bitcoin-core/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./bitcoin-core/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - bitcoin-core-db:/home/bitcoin/.bitcoin/regtest
    ports:
      - "127.0.0.1:38332:8332" # RPC
    networks:
      - botanix-local

networks:
  botanix-local:
    external: true

volumes:
  bitcoin-core-db:
    driver: local
