[package]
name = "botanix-authority-consensus"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
exclude = { workspace = true }
description = "A PoA consensus engine"

[dependencies]
alloy-rpc-types-engine = { workspace = true }
async-trait = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-eips = { workspace = true }
alloy-consensus = { workspace = true }

## Bitcoin
bitcoin = { workspace = true }

## Botanix
botanix-activation-manager = { workspace = true }
botanix-authority-edh = { workspace = true }
botanix-authority-metrics = { workspace = true }
botanix-authority-peg = { workspace = true, features = ["secp256k1"] }
botanix-authority-rsp = { workspace = true }
botanix-bitcoin-checkpoint = { workspace = true }
botanix-btc-wallet = { workspace = true }
botanix-chainspec = { workspace = true }
botanix-cli-args = { workspace = true }
botanix-comet-bft-rpc = { workspace = true }
botanix-data-parser = { workspace = true }
botanix-storage = { workspace = true }
botanix-consensus-common = { workspace = true }
btc-server = { workspace = true }
botanix-btc-server-client = { workspace = true }
botanix-evm = { workspace = true }

# others
bytes = "1.6.0"
displaydoc = "0.2"
ethabi = "18.0.0"

# frost
frost-secp256k1-tr = { workspace = true }
futures = { workspace = true }

# async
futures-util = { workspace = true }

hex = "0.4.3"

# lazy
once_cell = { workspace = true }
prost = "0.13.3"
reth-basic-payload-builder = { workspace = true }

# reth deps
reth-chain-state = { workspace = true }
reth-chainspec = { workspace = true }
reth-consensus = { workspace = true }
reth-consensus-common = { workspace = true }
reth-db = { workspace = true }
reth-ethereum-consensus = { workspace = true }
reth-ethereum = { workspace = true, features = ["rpc"] }
reth-ethereum-payload-builder = { workspace = true }
reth-evm = { workspace = true }
reth-evm-ethereum = { workspace = true }
reth-execution-errors = { workspace = true }
reth-network = { workspace = true, features = ["serde"] }
reth-network-peers = { workspace = true, features = ["secp256k1"] }
reth-node-core = { workspace = true }
reth-node-builder = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-payload-builder = { workspace = true }
reth-primitives = { workspace = true, features = ["secp256k1"] }
reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-revm = { workspace = true }
# reth-rpc-types = { workspace = true }
reth-tasks = { workspace = true }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-trie = { workspace = true }
reth-trie-db = { workspace = true }
reth-ethereum-primitives = { workspace = true }

# LRU Cache
schnellru = { workspace = true }

## Crypto
secp256k1 = { workspace = true, features = ["global-context", "recovery"] }

serde_json = { workspace = true }
tendermint = { version = "0.40.1", features = ["clock"] }

# Tendermint
tendermint-abci = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-rpc = { workspace = true }

## thiserror
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }

### Grpc
tonic = { workspace = true }
tracing = { workspace = true }

# uuid
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
botanix-storage = { workspace = true, features = ["test-utils"] }
rand = { workspace = true }
reth-cli-runner = { workspace = true }
reth-db-common = { workspace = true }
reth-evm = { workspace = true, features = ["test-utils"] }
