[package]
name = "botanix-consensus-common"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }

# other deps
alloy-primitives = { workspace = true }

# botanix deps
botanix-authority-edh = { workspace = true }
botanix-chainspec = { workspace = true }
# reth deps
reth-chainspec = { workspace = true }
reth-consensus = { workspace = true }
reth-primitives = { workspace = true, features = ["secp256k1"] }
reth-primitives-traits = { workspace = true }
reth-storage-api = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
rand = { workspace = true }
reth-storage-api = { workspace = true }

[lints]
workspace = true
