[package]
name = "botanix-storage"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Botanix storage implementation"

[features]
test-utils = ["reth-db/test-utils"]

[dependencies]
alloy-primitives = { workspace = true }

# others
arbitrary = { workspace = true }
auto_impl = { workspace = true }
bytes = { workspace = true }
ciborium = "0.2.1"
eyre = { workspace = true }
itertools = { workspace = true }
modular-bitfield = { workspace = true }
reth-codecs = { workspace = true }
# reth
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api = { workspace = true }
reth-execution-types = { workspace = true }
reth-node-types = { workspace = true }
reth-primitives = { workspace = true, features = ["reth-codec"] }
reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true }
reth-prune = { workspace = true }
reth-prune-types = { workspace = true }
reth-storage-api = { workspace = true }
reth-storage-errors = { workspace = true }
reth-trie-common = { workspace = true }
secp256k1 = { workspace = true, features = [
  "global-context",
  "rand",
  "recovery",
] }
serde = { workspace = true, default-features = false }
sha2 = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

# Botanix
botanix-primitives = { workspace = true }

# Botanix Trusted Execution Machine
botanix-tem = { git = "ssh://git@github.com/lamafab/botanix-tee.git", branch = "reth-integration-part2" }

[dev-dependencies]
arbitrary = { workspace = true }
proptest = { workspace = true }
proptest-arbitrary-interop = { workspace = true }
reth-primitives = { workspace = true, features = ["arbitrary"] }
tempfile = { workspace = true }
test-fuzz = { workspace = true }

[lints]
workspace = true
