name: Docker Build Test

on:
  pull_request:
    branches:
      - develop
      - hotfix
      - main
    types:
      - opened

jobs:
  build_btc_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t botanix_testnet_btc_server_v1 \
            -f Dockerfile \
            --build-arg PACKAGE=botanix-btc-server \
            --build-arg BIN=botanix-btc-server \
            .
        working-directory: ./

  build_reth_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t botanix_testnet_reth_node_v1 \
            -f Dockerfile \
            --build-arg PACKAGE=botanix-reth \
            --build-arg BIN=botanix-reth \
            .
        working-directory: ./
